import { useEffect, useState } from "react"
import Head from "next/head";
import styles from "../../styles/country.module.css"
import Link from "next/link"
import {AiOutlineArrowLeft} from "react-icons/ai"
import Loader from "../../components/Loader/Loader";
const Country = (props) => {
  console.log(props.info)
  const [country] = useState(props.info[0]) 

    const officialName = country?.name?.official
    const officialCurrencie = country?.currencies[Object?.keys(country.currencies)[0]]
    const officialLanguages = Object?.values(country?.languages)
    const capital = country?.capital === undefined? "none" : country?.capital[0]

    // const handleClick = (e) => {
    //   let newCountry = countries.filter(country => country.cca3 === e)
    //   //setDisplay(newCountry)
    // } 
    // const handleName = (e) => {
    //   let newCountry = countries.filter(country => country.cca3 === e)
    //   return newCountry[0].name.common
    // } 
  
   // const borders = !country.borders ? "no borders" : country.borders.map(border => <button className={ `light-bg-element ${styles.country__btn_border}`} key={border} onClick={()=>handleClick(border)}>{handleName(border)}</button>)
  if(props.info){
    return (
      <main className={styles.country__container}>
      <Head>
        <title>{officialName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Link href="/"><button  className={ `light-bg-element ${styles.country__btn}`}><AiOutlineArrowLeft /> Back</button></Link>
        <section className={styles.country__content}>
          <figure className={styles.imgFlag__container}>
            <img src={country.flags.svg} alt={country.name.common} className={styles.imgFlag} />
          </figure>
          <article className={styles.details}>
          <h1 className={styles.details__name}>{country.name.common}</h1>
          <div className={styles.details__container}>
            <ul>
              <li><span className={styles.bold}>Native Name:</span> {officialName[Object.keys(officialName)[0]].official}</li>
              <li><span className={styles.bold}>Population:</span> {country.population}</li>
              <li><span className={styles.bold}>Region:</span> {country.region}</li>
              <li><span className={styles.bold}>Sub Region:</span> {country.subregion}</li>
              <li><span className={styles.bold}>Capital:</span> {capital}</li>
            </ul>
            <ul>
              <li><span className={styles.bold}>Top Level Domain:</span> {country.tld[0]}</li>
              <li><span className={styles.bold}>Currencies:</span> {`${officialCurrencie.name} "${officialCurrencie.symbol}"`}</li>
              <li><span className={styles.bold}>Languages:</span> {officialLanguages.join(", ")}</li>
            </ul>
          </div>
          <div className={styles.border__container}>
           <span className={styles.bold}>Border Countries</span>
          </div>
          </article>
        </section>
      </main>
    )
  }
  return <main className={styles.container}><Loader /></main>
}

export default Country

const getAllCountries = async (header = "all") => {
  const res = await fetch(`https://restcountries.com/v3.1/${header}`)
  const data = await res.json()
  return data
}
/* encontrar y pasar como prop los nombres de los paises que comparten fronteras */
export async function getStaticProps(context) {
  const country = context.params.country.split("-")
  if(country.length === 1){
    const data = await getAllCountries(`name/${country}`)
  
    return {
      props: {
        info: data
      }
    }
  } 

  const data = await getAllCountries()
  const fullName = context.params.country.replaceAll("-", " ")
  const match = data.filter(e => e.name.common.includes(fullName) === true )

  return {
    props: {
      info: match
    }
  }
}

export async function getStaticPaths() {
  const data = await getAllCountries()

  const countriesNames = data.map( e => ({params: {country: e.name.common.replaceAll(" ","-")}}))
  return {
    paths: countriesNames,
    fallback: false // See the "fallback" section below
  };
}